
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int id { get; set; }

    public string fullName { get; set; }

    public System.DateTime initiationDate { get; set; }

    public int fk_hiredfor { get; set; }

    public string email { get; set; }

    public string cellphone { get; set; }

    public System.DateTime startDate { get; set; }

    public string service_equipmentneeded { get; set; }

    public string aditional_service { get; set; }

    public Nullable<int> fk_companylist { get; set; }

    public string another_company { get; set; }

    public string aditional_info { get; set; }

    public string another_building { get; set; }

    public string restricted_access { get; set; }

    public string hiringManagerEmail { get; set; }

    public Nullable<int> fk_buildingaccess { get; set; }



    public virtual BeingHiredFor BeingHiredFor { get; set; }

    public virtual Building Building { get; set; }

    public virtual Company Company { get; set; }

}

}
