
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeDetail
{

    public int id { get; set; }

    public string fullName { get; set; }

    public string email { get; set; }

    public string cellphone { get; set; }

    public string service_equipmentneeded { get; set; }

    public string aditional_service { get; set; }

    public string hiringManagerEmail { get; set; }

    public string restricted_access { get; set; }

    public string another_building { get; set; }

    public string companyName { get; set; }

    public string buildingName { get; set; }

    public string beinghiredFor { get; set; }

}

}
